### ISSUE TITLE
Подготовить обзор статьи

### ISSUE THREAD

**Issue by aromanenko** [aromanenko/RobustPED#8]
https://hal.archives-ouvertes.fr/hal-01942038/document

Machine Learning Methods to Perform Pricing Optimization. A Comparison with Standard GLMs

Может ли она быть полезной при решении вопросов об определении цены, когда PED модель неадекватна?

**Comment by mh1m** [comment]
[проект.pptx](https://github.com/aromanenko/RobustPED/files/5828716/default.pptx)
